name: AutoQueue

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: windows-2019
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install requirements & webdriver
      run: |
        pip install -r requirements.txt
        wget https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_linux64.zip
        unzip chromedriver_linux64
        sudo cp chromedriver /usr/bin
        sudo chmod +x /usr/bin/chromedriver
    - name: Run script        # This doesn't work well currently. It will have no any display if headless mode is enabled in main.py for chromedriver
      env: 
        sessionid: ${{ secrets.sessionid }}
        steamRememberLogin: ${{ secrets.steamRememberLogin }}
        steamMachineAuth: ${{ secrets.steamMachineAuth }}
        steamLoginSecure: ${{ secrets.steamLoginSecure }}
        browserid: ${{ secrets.browserid }}
        steamID64: ${{ secrets.steamID64 }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
      run: |
        python3 main.py